# bash_profile will be used once, at "login" shells (eg. when login from
# another host, or login at the text console of a local unix machine).
#
if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi

# load all files from .dotfiles/shellrc/login.d directory
if [ -d $HOME/.dotfiles/shellrc/login.d ]; then
  for file in $HOME/.dotfiles/shellrc/login.d/*.sh; do
    source $file
  done
fi
